networks:
   products-network:
      driver: bridge

services:
   products-api:
      build:
          context: .   
          dockerfile: Dockerfile
      ports:
          - "8081:8081"
      depends_on:
          - postgres
          - rabbitmq
      networks:
          - products-network

   postgres:
      image: postgres:latest
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: coti
         POSTGRES_DB: bdproductsapi
      ports:
         - "5432:5432"
      networks:
          - products-network

   rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
          - products-network
