#Descrição da configuração de deploy
name: Pipeline para Deploy da aplicação no AWS

#Definir o evento que irá gerar a publicação do projeto
on:
   push: #realizar un push no github
     branches: #branch principal
        - main
   pull_request: #realizar um pull request
     branches: #branch principal
        - main

#Definir as tarefas que serão feitas após o push
jobs:

    build: #compilação do projeto
       name: Compilação do projeto Spring Boot
       runs-on: ubuntu-latest #Servidor linux
       steps:
          #Checkout do código
          - name: Checkout do código
            uses: actions/checkout@v2

          #Setup para compilar o projeto
          - name: Configuração do JDK 21
            uses: actions/setup-java@v2
            with:
                java-version: "21"
                distribution: "temurin"
          
          #Build do projeto usando o maven
          - name: Compilar o projeto com o Maven
            run: mvn clean package -DskipTests

          #Pegar os arquivos compilados do diretório /target
          - name: Pegar os arquivos da pasta target
            run: ls -la target

          #Upload dos arquivos
          - name: Gerando o arquivo JAR compilado do projeto
            uses: actions/upload-artifact@v3
            with:
                name: jar-file
                path: target/*.jar 

    test: #teste do projeto
       name: Execução dos testes
       runs-on: ubuntu-latest #Servidor linux
       needs: build #etapa do teste é executada após o build
       steps:
          #Checkout do código
          - name: Checkout do código
            uses: actions/checkout@v2

          #Setup para compilar o projeto
          - name: Configuração do JDK 21
            uses: actions/setup-java@v2
            with:
                java-version: "21"
                distribution: "temurin"
          
          #Executar os testes do projeto
          - name: Executar testes com Maven
            run: mvn test surefire-report:report

          #Ler os arquivos gerados
          - name: Listar os arquivos do diretório target/site
            run: ls -la target/site

          #Upload do relatório de testes
          - name: Upload do relatório de testes
            uses: action/upload-artifact@v4
            with:
              name: test-reports
              path: target/site/surefire-report.html
